#! /usr/bin/python

"""
Wake on LAN script
"""

import struct
import socket

# Configuration variables
BROADCAST = ['192.168.1.255', '192.168.0.255']
WOL_PORT = 9

known_computers = {
'server'     : '8c:dc:d4:34:32:83',
}

def wake_on_lan(ethernet_address):
    """
    Send magic packet to specitied mac address
    """

    # Construct 6 byte hardware address
    add_oct = ethernet_address.split(':')
    if len(add_oct) != 6:
        print("\n*** Illegal MAC address\n")
        print("MAC should be written as 00:11:22:33:44:55\n")
        return
    hwa = struct.pack('BBBBBB', int(add_oct[0],16),
      int(add_oct[1],16),
      int(add_oct[2],16),
      int(add_oct[3],16),
      int(add_oct[4],16),
      int(add_oct[5],16))

    # Build magic packet

    msg = b'\xff' * 6 + hwa * 16

    # Send packet to broadcast address using UDP port 9

    soc = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    soc.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST,1)
    for i in BROADCAST:
        soc.sendto(msg,(i,WOL_PORT))
    soc.close()

if __name__ == '__main__':
    wake_on_lan(known_computers['server'])
    print("\nDone! The computer should be up and running in a short while.")
